# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'W.D.R.KAWSHALYA- COBSCCOMP182P-001' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for W.D.R.KAWSHALYA- COBSCCOMP182P-001

  target 'W.D.R.KAWSHALYA- COBSCCOMP182P-001Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'W.D.R.KAWSHALYA- COBSCCOMP182P-001UITests' do
    # Pods for testing
  end

 pod 'Firebase/Core'
 pod 'Firebase/Database' 
 pod 'Firebase/Analytics' 
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'Firebase/Storage'

end
